## Numpy array and basics
learn about numpy

In [12]:
import numpy as np

### creating array from list


In [13]:
arr_1d =np.array([1,2,3,4,5])
print("1D array : ",arr_1d)
arr_2d =np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

1D array :  [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs numpy Array

In [14]:
py_list = [1,2,3]
print("Python list multiplication",py_list * 2)
np_array = np.array([1,2,3])
print("Python array multiplication",np_array *2)
import time 
start =time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time :",time.time()-start)
start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time:",time.time()-start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 list operation time : 0.054841041564941406

 Numpy operation time: 0.0071146488189697266


### creating array from scratch


In [15]:
zeros = np.zeros((3,4))
print("zeros array:\n",zeros)
ones = np.ones((2,3))
print("one array:\n",ones)
full = np.full((2,2),7)
print("full array:\n",full)
random = np.random.random((2,3))
print("random array:\n",random)
sequence = np.arange(0,10 )

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array:
 [[0.63237509 0.9530496  0.63028667]
 [0.19908318 0.93646532 0.33166593]]


Vector,Matrix and Tensor 


In [16]:
vector = np.array([1,2,3])
print("Vector:",vector)
matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix:",matrix)
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor:",tensor)

Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape",arr.shape)
print("size",arr.size)
print("Dimension",arr.ndim)
print("DType",arr.dtype)

shape (2, 3)
size 6
Dimension 2
DType int64


## Array Reshaping 

In [18]:
arr = np.arange(12)
print("Original array",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped aaray",reshaped)
flattened = reshaped.flatten()
print("\n Flattened array",flattened)
raveled = reshaped.ravel()
print("\n reveled array",raveled) 
transpose = reshaped.T
print("\n Transposed array", transpose)




Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped aaray [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
